spring:
  ## 数据源
  datasource:
    dynamic:
      ## 默认数据源
      primary: master
      strict: false
      datasource:
        ## 主库配置
        master:
          url: jdbc:mysql://127.0.0.1:3306/pear-admin-pro?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT
          username: root
          password: root
      ## 连接池配置
      hikari:
        max-lifetime: 30000
        min-idle: 3
        max-pool-size: 10
        connection-test-query: SELECT 1

  ## Redis 缓存
  redis:
    ## 默认数据库
    database: 2
    ## 配置信息
    host: 127.0.0.1
    port: 6379
    password:
    ## 超时时间
    timeout: 3000
    ## 连接池配置
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 6
        min-idle: 0

  ## 定时任务
  quartz:
    # 将任务等保存化到数据库
    job-store-type: jdbc
    # 程序结束时会等待quartz相关的内容结束
    wait-for-jobs-to-complete-on-shutdown: true
    # QuartzScheduler 启动时更新己存在的Job
    overwrite-existing-jobs: true
    # 详细配置
    properties:
      org:
        quartz:
          # scheduler相关
          scheduler:
            # scheduler的实例名
            instanceName: scheduler
            instanceId: AUTO
          # 持久化相关
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            useProperties: false
          # 线程池相关
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            # 线程数
            threadCount: 10
            # 线程优先级
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
