## tomcat 配置
server:
  ## 监听端口
  port: 9191

## spring 配置
spring:
  profiles:
    ## 激活配置
    active: dev

## mybatis 配置
mybatis-plus:
  ## mapper 文件位置
  mapper-locations: classpath*:com/pearadmin/pro/modules/**/xml/**.xml
  ## domain 实体别名
  type-aliases-package: com.pearadmin
  configuration:
    ## SQL 执行日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

## 分页工具
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

