## tomcat 配置
server:
  ## 监听端口
  port: 9292

## Spring 配置
spring:
  ## 动态配置
  profiles:
    ## 状态
    active: dev
  ## 邮件配置
  mail:
    ## 协议
    protocol: smtp
    ## 地址
    host: smtp.qq.com
    ## 端口
    port: 587
    ## 账户
    username: 854085467@qq.com
    ## 密钥
    password:
    ## 字符集
    default-encoding: UTF-8
    ## 测试
    test-connection: true
    ## 来源
    from: 854085467@qq.com

## mybatis 配置
mybatis-plus:
  ## 文件位置
  mapper-locations: classpath*:com/pearadmin/pro/modules/**/xml/**.xml
  ## 实体别名
  type-aliases-package: com.pearadmin
  ## 日志打印
  configuration:
    ## 日志实现
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

## Helper 配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

## 资源存储
upload:
  ## 存储位置 aliyun
  location: aliyun

## 阿里云 Oss 存储
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId:
    accessKeySecret: 
    bucketName: pear-admin